name: yatrasahayatri
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  simple_animations: 4.0.0
  flutter_svg: 2.0.4
  persistent_bottom_nav_bar: 5.0.2
  flutter_rating_bar: 4.0.1
  email_validator: 2.1.17
  flutter_easyloading: 3.0.5
  permission_handler: any
  # package_info_plus: 4.0.0

  #State management
  provider: 6.0.5

  #Location
  geolocator: 9.0.2
  google_maps_flutter: 2.2.5
  flutter_google_places: 0.3.0

  #RestApi
  http: 0.13.5
  shared_preferences: 2.1.0
  connectivity_plus: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
